import type { NextPage } from "next";
import Head from "next/head";
import Box from "@mui/material/Box";
import { Container } from "@mui/material";
import Link from 'next/link'
import { GetStaticProps } from "next";
import { InferGetStaticPropsType } from 'next'

export const getStaticProps: GetStaticProps = async () => {
  const allPostsData = [1, 2, 3, 4, 5]
  return {
    props: {
      allPostsData
    }
  }
};

const Home: NextPage = ({ allPostsData }: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <Container maxWidth="md">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="title">
        Read{' '}
        <Link href="/">
          tes
        </Link>
      </h1>
      <Box>
        {allPostsData.map(function (item: number, i: number) {
          return <li key={i}>{item}</li>
        })}
      </Box>
    </Container>
  );
};

export default Home;